version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
    ports:
      - '30011:3306'
    volumes:
      - db:/var/lib/mysql
  php:
    build: ./php
    ports:
      - '30010:80'
    volumes:
      - ../wordpress-project:/var/www/html
    depends_on:
      - mysql
volumes:
  db:
